fix: issue#31: checks if the width and height are negative and returns 0 if so, otherwise returns calculated values
Hexastack/eazychart pull request #34
Opened 2022-10-01 13:35 UTC by AlanLes

# Motivation

Regarding issue #31

Fixes [#31](https://github.com/Hexastack/eazychart/issues/31)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have done the work for both react and vue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (Storybook)
- [-] I have added unit tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-10-01 16:52 UTC, marrouchi requested changes
@AlanLes Many thanks for your contribution ! :pray:

2022-10-01 16:52 UTC, marrouchi commented on packages/ez-react/src/components/Chart.tsx
> +      height: height >= 0 ? height : 0,
```suggestion
      width: Math.max(width, 0),
      height: Math.max(height, 0),
```
Mind updating this also in vue ?

2022-10-01 17:38 UTC, AlanLes commented
@marrouchi, I have some issues with committing, I can't commit changes, any ideas about what's going on? 🤔 😞 
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/13744352/193421428-d728d0fe-478d-4692-901c-09a9d83e214b.png">

2022-10-02 08:30 UTC, marrouchi commented
> @marrouchi, I have some issues with committing, I can't commit changes, any ideas about what's going on? thinking disappointed <img alt="image" width="1017" src="https://user-images.githubusercontent.com/13744352/193421428-d728d0fe-478d-4692-901c-09a9d83e214b.png">

@AlanLes Once you cloned the project did you run the command `yarn setup` ? This should install all dependencies.

2022-10-02 14:06 UTC, AlanLes commented
Good point, huge thanks, it's finished 👌 🙂

2022-10-02 15:17 UTC, AlanLes commented on packages/ez-react/src/components/Chart.tsx
> +      height: height >= 0 ? height : 0,
Okay, it's done! ;)

2022-10-02 15:21 UTC, marrouchi approved these changes
Awesome !

2022-10-02 15:27 UTC, merged