fix: issue templates
Hexastack/eazychart pull request #56
Opened 2022-10-07 14:58 UTC by IlyesBenAmara

# Motivation
Edited the issue template

2022-10-08 20:17 UTC, marrouchi requested changes

2022-10-08 20:17 UTC, marrouchi commented on .github/ISSUE_TEMPLATE/Bug_report.yml
> +  "help-needed"
Why did you change the label ?

2022-10-08 21:36 UTC, marrouchi requested changes

2022-10-08 21:36 UTC, marrouchi commented on .github/ISSUE_TEMPLATE/Bug_report.yml
>  title: "🐛 [BUG] - @eazychart-[core | react | vue]- <title>"
```suggestion
title: "🐛 [BUG] eazychart-[css | core | react | vue] - <title>"
```

2022-10-08 21:36 UTC, marrouchi commented on .github/ISSUE_TEMPLATE/Bug_report.yml
>  title: "🐛 [BUG] - @eazychart-[core | react | vue]- <title>"
Let's do the same for the others.

2022-10-11 07:50 UTC, IlyesBenAmara commented
Will close this PR in favor of #66 since this branch was not properly rebased

2022-10-11 07:50 UTC, closed without merging